setup:
  template:
    name: "cdl"
    fields: "fields.min.yml"
    pattern: "cdl-%{[agent.version]}"

filebeat.inputs:
  - type: unix
    id: cdl
    enabled: true
    path: "/tmp/filebeat/filebeat.sock"
    max_message_size: 10MiB
    line_delimiter: "\n"
    socket_type: datagram

output.elasticsearch:
  hosts: ["http://${ELASTICSEARCH_HOST}:9200"]
  index: "cdl-%{[agent.version]}"

processors:
  - add_locale: ~
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - decode_csv_fields:
      fields:
        message: message
      separator: ","
      ignore_missing: false
      overwrite_keys: true
      trim_leading_space: false
      fail_on_error: true
  - extract_array:
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        panw.created: 0
        panw.serial: 1
        panw.type: 2
        panw.subtype: 3

  - extract_array:
      when:
        equals:
          panw.type: TRAFFIC
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        time_generated: 5
        src.ip: 6
        dst.ip: 7
        nat.src.ip: 8
        nat.dst.ip: 9
        rule_matched: 10
        src.user: 11
        dst.user: 12
        app: 13
        vsys: 14
        from_zone: 15
        to_zone: 16
        inbound_if: 17
        outbound_if: 18
        log_set: 19
        session_id: 20
        count_of_repeats: 21
        src.port: 22
        dst.port: 23
        nat.src.port: 24
        nat.dst.port: 25
        proto: 26
        action: 27
        bytes.total: 28
        bytes.sent: 29
        bytes.received: 30
        packets.total: 31
        session_start_time: 32
        total_time_elapsed: 33
        url_category: 34
        sequence_no: 35
        src.location: 36
        dst.location: 37
        packets.sent: 38
        packets.received: 39
        session_end_reason: 40
        dg_hier.level_1: 41
        dg_hier.level_2: 42
        dg_hier.level_3: 43
        dg_hier.level_4: 44
        vsys_name: 45
        log_source: 46
        action_source: 47
        src.uuid: 48
        dst.uuid: 49
        tunnelid_imsi: 50
        monitor_tag_imei: 51
        parent.session_id: 52
        parent.start_time: 53
        tunnel: 54
        ep_assoc_id: 55
        chunks.total: 56
        chunks.sent: 57
        chunks.received: 58
        rule_matched_uuid: 59
        http2_connection: 60
        link_change_count: 61
        sdwan.policy_id: 62
        link_switches: 63
        sdwan.cluster: 64
        sdwan.device_type: 65
        sdwan.cluster_type: 66
        sdwan.site: 67
        dynusergroup_name: 68
        xff_ip: 69
        src.device.category: 70
        src.device.profile: 71
        src.device.model: 72
        src.device.vendor: 73
        src.device.osfamily: 74
        src.device.osversion: 75
        src.device.host: 76
        src.device.mac: 77
        dst.device.category: 78
        dst.device.profile: 79
        dst.device.model: 80
        dst.device.vendor: 81
        dst.device.osfamily: 82
        dst.device.osversion: 83
        dst.device.host: 84
        dst.device.mac: 85
        container_id: 86
        pod.namespace: 87
        pod.name: 88
        src.edl: 89
        dest.edl: 90
        host_id: 91
        endpoint_serial_number: 92
        src.dynamic_address_group: 93
        dst.dynamic_address_group: 94
        ha_session_owner: 95
        time_generated_high_res: 96
        nssai.network_slice.type: 97
        nssai.network_slice.differentiator: 98

  - extract_array:
      when:
        and:
          - equals:
              panw.type: THREAT
          - or:
              - equals:
                  panw.subtype: vulnerability
              - equals:
                  panw.subtype: spyware
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        time_generated: 5
        src.ip: 6
        dst.ip: 7
        nat.src.ip: 8
        nat.dst.ip: 9
        rule_matched: 10
        src.user: 11
        dst.user: 12
        app: 13
        vsys: 14
        from_zone: 15
        to_zone: 16
        inbound_if: 17
        outbound_if: 18
        log_set: 19
        session_id: 20
        count_of_repeats: 21
        src.port: 22
        dst.port: 23
        nat.src.port: 24
        nat.dst.port: 25
        proto: 26
        action: 27
        file_name: 28
        threat_id: 29
        vendor_severity: 30
        direction_of_attack: 31
        sequence_no: 32
        src.location: 33
        dst.location: 34
        pcap_id: 35
        file_hash: 36
        cloud: 37
        url_idx: 38
        file_type: 39
        email.sender: 40
        email.subject: 41
        email.recipient: 42
        report_id: 43
        dg_hier.level_1: 44
        dg_hier.level_2: 45
        dg_hier.level_3: 46
        dg_hier.level_4: 47
        vsys_name: 48
        log_source: 49
        src.uuid: 50
        dst.uuid: 51
        tunnelid_imsi: 52
        monitor_tag_imei: 53
        parent.session_id: 54
        parent.start_time: 55
        tunnel: 56
        threat_category: 57
        content_version: 58
        sig_flags: 59
        rule_matched_uuid: 60
        http2_connection: 61
        dynusergroup_name: 62
        xff_ip: 63
        src.device.category: 64
        src.device.profile: 65
        src.device.model: 66
        src.device.vendor: 67
        src.device.osfamily: 68
        src.device.osversion: 69
        src.device.host: 70
        src.device.mac: 71
        dst.device.category: 72
        dst.device.profile: 73
        dst.device.model: 74
        dst.device.vendor: 75
        dst.device.osfamily: 76
        dst.device.osversion: 77
        dst.device.host: 78
        dst.device.mac: 79
        container_id: 80
        pod.namespace: 81
        pod.name: 82
        src.edl: 83
        dest.edl: 84
        host_id: 85
        endpoint_serial_number: 86
        domain_edl: 87
        src.dynamic_address_group: 88
        dst.dynamic_address_group: 89
        partial_hash: 90
        time_generated_high_res: 91
        nssai.network_slice.type: 92

  - extract_array:
      when:
        and:
          - equals:
              panw.type: THREAT
          - equals:
              panw.subtype: url
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        time_generated: 5
        src.ip: 6
        dst.ip: 7
        nat.src.ip: 8
        nat.dst.ip: 9
        rule_matched: 10
        src.user: 11
        dst.user: 12
        app: 13
        vsys: 14
        from_zone: 15
        to_zone: 16
        inbound_if: 17
        outbound_if: 18
        log_set: 19
        session_id: 20
        count_of_repeats: 21
        src.port: 22
        dst.port: 23
        nat.src.port: 24
        nat.dst.port: 25
        proto: 26
        action: 27
        url: 28
        url_category: 29
        vendor_severity: 30
        direction_of_attack: 31
        sequence_no: 32
        src.location: 33
        dst.location: 34
        content_type: 35
        pcap_id: 36
        url_idx: 37
        user_agent: 38
        xff: 39
        referer: 40
        dg_hier.level_1: 41
        dg_hier.level_2: 42
        dg_hier.level_3: 43
        dg_hier.level_4: 44
        vsys_name: 45
        log_source: 46
        src.uuid: 47
        dst.uuid: 48
        http_method: 49
        tunnelid_imsi: 50
        monitor_tag_imei: 51
        parent.session_id: 52
        parent.start_time: 53
        tunnel: 54
        inline_ml_verdict: 55
        content_version: 56
        sig_flags: 57
        http_headers: 58
        url_category_list: 59
        rule_matched_uuid: 60
        http2_connection: 61
        dynusergroup_name: 62
        xff_ip: 63
        src.device.category: 64
        src.device.profile: 65
        src.device.model: 66
        src.device.vendor: 67
        src.device.osfamily: 68
        src.device.osversion: 69
        src.device.host: 70
        src.device.mac: 71
        dst.device.category: 72
        dst.device.profile: 73
        dst.device.model: 74
        dst.device.vendor: 75
        dst.device.osfamily: 76
        dst.device.osversion: 77
        dst.device.host: 78
        dst.device.mac: 79
        container_id: 80
        pod.namespace: 81
        pod.name: 82
        src.edl: 83
        dest.edl: 84
        host_id: 85
        endpoint_serial_number: 86
        src.dynamic_address_group: 87
        dst.dynamic_address_group: 88
        time_generated_high_res: 89
        nssai.network_slice.type: 90

  - extract_array:
      when:
        and:
          - equals:
              panw.type: THREAT
          - equals:
              panw.subtype: file
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        time_generated: 5
        src.ip: 6
        dst.ip: 7
        nat.src.ip: 8
        nat.dst.ip: 9
        rule_matched: 10
        src.user: 11
        dst.user: 12
        app: 13
        vsys: 14
        from_zone: 15
        to_zone: 16
        inbound_if: 17
        outbound_if: 18
        log_set: 19
        session_id: 20
        count_of_repeats: 21
        src.port: 22
        dst.port: 23
        nat.src.port: 24
        nat.dst.port: 25
        proto: 26
        action: 27
        file_name: 28
        url_category: 29
        vendor_severity: 30
        direction_of_attack: 31
        sequence_no: 32
        src.location: 33
        dst.location: 34
        pcap_id: 35
        file_hash: 36
        report_id: 37
        dg_hier.level_1: 38
        dg_hier.level_2: 39
        dg_hier.level_3: 40
        dg_hier.level_4: 41
        vsys_name: 42
        log_source: 43
        src.uuid: 44
        dst.uuid: 45
        tunnelid_imsi: 46
        monitor_tag_imei: 47
        parent.session_id: 48
        parent.start_time: 49
        tunnel: 50
        content_version: 51
        sig_flags: 52
        rule_matched_uuid: 53
        http2_connection: 54
        dynusergroup_name: 55
        xff_ip: 56
        src.device.category: 57
        src.device.profile: 58
        src.device.model: 59
        src.device.vendor: 60
        src.device.osfamily: 61
        src.device.osversion: 62
        src.device.host: 63
        src.device.mac: 64
        dst.device.category: 65
        dst.device.profile: 66
        dst.device.model: 67
        dst.device.vendor: 68
        dst.device.osfamily: 69
        dst.device.osversion: 70
        dst.device.host: 71
        dst.device.mac: 72
        container_id: 73
        pod.namespace: 74
        pod.name: 75
        src.edl: 76
        dest.edl: 77
        host_id: 78
        endpoint_serial_number: 79
        domain_edl: 80
        src.dynamic_address_group: 81
        dst.dynamic_address_group: 82
        partial_hash: 83
        time_generated_high_res: 84
        reason_for_filtering_action: 85
        justification: 86
        nssai.network_slice.type: 87

  - extract_array:
      when:
        equals:
          panw.type: HIPMATCH
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        time_generated: 5
        src.user: 6
        vsys: 7
        endpoint.device_name: 8
        endpoint.os_type: 9
        src.ip: 10
        hip.match_name: 11
        count_of_repeats: 12
        hip.match_type: 13
        sequence_no: 14
        dg_hier.level_1: 15
        dg_hier.level_2: 16
        dg_hier.level_3: 17
        dg_hier.level_4: 18
        vsys_name: 19
        log_source: 20
        vsys_id: 21
        src.ipv6: 22
        host_id: 23
        endpoint_serial_number: 24
        src.device.category: 25
        src.device.profile: 26
        src.device.model: 27
        src.device.vendor: 28
        src.device.osfamily: 29
        src.device.osversion: 30
        src.device.mac: 31
        src.device.host: 32
        source: 33
        timestamp_device_identification: 34
        time_generated_high_res: 35

  - extract_array:
      when:
        equals:
          panw.type: GLOBALPROTECT
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        time_generated: 5
        vsys: 6
        event_id: 7
        stage: 8
        auth_method: 9
        tunnel_type: 10
        src.user: 11
        src.region: 12
        endpoint.device_name: 13
        public_ipv4: 14
        public_ipv6: 15
        private_ipv4: 16
        private_ipv6: 17
        host_id: 18
        endpoint_serial_number: 19
        endpoint.gp_version: 20
        endpoint.os_type: 21
        endpoint.os_version: 22
        count_of_repeats: 23
        quarantine_reason: 24
        connection_error: 25
        description: 26
        event_status: 27
        endpoint.gp_gateway_location: 28
        login_duration: 29
        connection.method: 30
        connection.error_id: 31
        endpoint.gp_portal: 32
        sequence_no: 33
        time_generated_high_res: 34
        endpoint.gp_selection_type: 35
        ssl_response_time: 36
        endpoint.gp_gateway_priority: 37
        endpoint.gp_gateway_attempted: 38
        endpoint.gp_gateway: 39
        dg_hier.level_1: 40
        dg_hier.level_2: 41
        dg_hier.level_3: 42
        dg_hier.level_4: 43
        vsys_name: 44
        log_source: 45
        vsys_id: 46

  - extract_array:
      when:
        equals:
          panw.type: USERID
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        time_generated: 5
        vsys: 6
        src.ip: 7
        src.user: 8
        mapping.data_source_name: 9
        event_id: 10
        count_of_repeats: 11
        mapping.timeout: 12
        src.port: 13
        dst.port: 14
        mapping.data_source: 15
        mapping.data_source_type: 16
        sequence_no: 17
        dg_hier.level_1: 18
        dg_hier.level_2: 19
        dg_hier.level_3: 20
        dg_hier.level_4: 21
        vsys_name: 22
        log_source: 23
        vsys_id: 24
        mfa_factor_type: 25
        auth.completion_time: 26
        auth.factor_no: 27
        ug_flags: 28
        user_identified_by_source: 29
        tag: 30
        time_generated_high_res: 31

  - extract_array:
      when:
        equals:
          panw.type: DECRYPTION
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        time_generated: 5
        src.ip: 6
        dst.ip: 7
        nat.src.ip: 8
        nat.dst.ip: 9
        rule_matched: 10
        src.user: 11
        dst.user: 12
        app: 13
        vsys: 14
        from_zone: 15
        to_zone: 16
        inbound_if: 17
        outbound_if: 18
        log_set: 19
        time_received_management_plane: 20
        session_id: 21
        count_of_repeats: 22
        src.port: 23
        dst.port: 24
        nat.src.port: 25
        nat.dst.port: 26
        proto: 27
        action: 28
        tunnel: 29
        src.uuid: 30
        dst.uuid: 31
        rule_matched_uuid: 32
        client_to_firewall: 33
        firewall_to_client: 34
        tls.version: 35
        tls.key_exchange: 36
        tls.encryption_algo: 37
        tls.auth: 38
        tls.policy_name: 39
        tls.elliptic_curve: 40
        error_index: 41
        root_status: 42
        chain_status: 43
        proxy_type: 44
        certificate_serial: 45
        fingerprint: 46
        tls.time_not_before: 47
        tls.time_not_after: 48
        tls.certificate_version: 49
        tls.certificate_size: 50
        tls.common_name_length: 51
        tls.issuer_name_length: 52
        tls.root_common_name_length: 53
        tls.sni_length: 54
        tls.certificate_flags: 55
        tls.common_name: 56
        tls.issuer_common_name: 57
        tls.root_common_name: 58
        tls.sni: 59
        error_message: 60
        container_id: 61
        pod.namespace: 62
        pod.name: 63
        src.edl: 64
        dest.edl: 65
        src.dynamic_address_group: 66
        dst.dynamic_address_group: 67
        time_generated_high_res: 68
        src.device.category: 69
        src.device.profile: 70
        src.device.model: 71
        src.device.vendor: 72
        src.device.osfamily: 73
        src.device.osversion: 74
        src.device.host: 75
        src.device.mac: 76
        dst.device.category: 77
        dst.device.profile: 78
        dst.device.model: 79
        dst.device.vendor: 80
        dst.device.osfamily: 81
        dst.device.osversion: 82
        dst.device.host: 83
        dst.device.mac: 84
        sequence_no: 85

  - extract_array:
      when:
        equals:
          panw.type: SYSTEM
      field: message
      overwrite_keys: true
      omit_empty: true
      mappings:
        config_version: 4
        event_time: 5
        vsys: 6
        event_name: 7
        event_component: 8
        vendor_severity: 9
        event.description: 10
        sequence_no: 11
        dg_hier.level_1: 12
        dg_hier.level_2: 13
        dg_hier.level_3: 14
        dg_hier.level_4: 15
        vsys_name: 16
        log_source: 17
        device_group: 18
        template: 19
        time_generated_high_res: 20

  - timestamp:
      field: time_generated_high_res
      layouts:
        - '2006-01-02T15:04:05Z'
        - '2006-01-02T15:04:05.999Z'
        - '2006-01-02T15:04:05.999-07:00'
      ignore_failure: no

  - drop_fields:
      fields: ["message"]
